categories:
  mediaconsent:
    label: 'mediaconsent'
  mediaconsent.templates:
    label: 'Templates'
    parent: mediaconsent
  mediaconsent.pages:
    label: 'Pages'
    parent: mediaconsent

settings:
  mediaconsent.templateRootPath:
    label: 'Templates'
    category: mediaconsent.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:mediaconsent/Resources/Private/Templates/'
  mediaconsent.partialRootPath:
    label: 'Partials'
    category: mediaconsent.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:mediaconsent/Resources/Private/Partials/'
  mediaconsent.layoutRootPath:
    label: 'Layouts'
    category: mediaconsent.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:mediaconsent/Resources/Private/Layouts/'
  mediaconsent.reloadPageType:
    label: 'Reload Page Type'
    category: mediaconsent.pages
    description: ''
    type: int
    default: 122
